### ISSUE TITLE
Broken in HC2 version 4.070?

### ISSUE THREAD

**Issue by zupermik** [ilcato/homebridge-Fibaro-HC2#3]
It seems that the plugin was broken after upgrading Fibaro HC2 to currently latest release 4.070.

Verifications from others are perhaps needed.

**Comment by ilcato** [comment]
upgrading and checking ...

**Comment by ilcato** [comment]
@zupermik, what kind of problem do you have?

**Comment by Debug1Bug** [comment]
Just upgraded my Fibaro HC2. Seems to work OK here.
However, would be nice to be able to control the services type so that i.e. switches would respond to "switch on lights in xxxx". Currently I have to say "switch on all units in xxxx". Except for my RGBW controllers that are correctly identified as lights. Any tips on how to do that?

**Comment by ilcato** [comment]
I upgraded too without problems.

**Comment by ilcato** [comment]
@Debug1Bug: in order to allow that kind of control you need to configure the type of load the switch (lightbulb, fan, ...) control through the an HomeKit iOs app, I cannot assume that a Switch control a light. Almost all of the apps available allows this configuration but the way in which it is performed is different.

**Comment by Debug1Bug** [comment]
@ilcato: Ok, I'm using the MyTouchHome app and I have not found a way to configure that, will keep looking. But in the HC2, under "Advanced" for the devices, there is actually a property called "Controlled load". This property is used to specify the type of load connected to the switch. I just thought that if this property was exposed through the HC2 API, it could actually be achieved.

**Comment by Debug1Bug** [comment]
Found the option in the Elgato Eve app. So now all lights respond to the "lights" command.
Thanks for a fantastic piece of software, it makes the home even smarter. Guys like you, makes a difference.

**Comment by zupermik** [comment]
Sorry for any inconvenience guys. Today everything is working. Really strange. 

Again, sorry, but I wanted to ensure that no one ended up with a broken system. 

Anyone that can share some thoughts why it started working after a while without any changes to homebridge or HC2? As I restarted homebridge after the upgrade, I assume that there is no caching involved on that side. 

I keep this ticket open for additional comments for a while if that's okey.
